spring.application.name=AgendaPro

spring.datasource.url=jdbc:postgresql://localhost:5432/agendapro
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=chave-do-token
mercadopago.access-token=APP_USR-93701423067637-060119-820e550bea0dc7466eda7fc8bc86604b-3442107853
app.frontend-url=http://localhost:4200